gz_bridge:
  ros__parameters:
    use_sim_time: true
    
    lazy: false
    queue_size: 10
    
    wait_for_lazy_tf: true
    
    qos_overrides:
      /camera/image_raw:
        reliability: best_effort
        durability: volatile
        depth: 60
      
      /camera/depth/image:
        reliability: best_effort
        durability: volatile
        depth: 60
      
      /camera/camera_info:
        reliability: best_effort
        durability: volatile
        depth: 10
        
      /camera/depth/points:
        reliability: best_effort
        durability: volatile
        depth: 10
