
rtabmap:
  ros__parameters:
    use_sim_time: true
    
    subscribe_depth: true
    subscribe_rgb: true
    subscribe_scan: false
    subscribe_scan_cloud: true
    subscribe_stereo: false
    subscribe_imu: true
    
    frame_id: "base_link"
    odom_frame_id: "odom"
    map_frame_id: "map"
    
    queue_size: 10
    approx_sync: true
    
    Rtabmap/DetectionRate: "1.0"
    Rtabmap/TimeThr: "0"
    Rtabmap/MemoryThr: "0"
    Rtabmap/StartNewMapOnLoopClosure: "false"
    Rtabmap/StartNewMapOnGoodSignature: "false"
    
    Mem/RehearsalSimilarity: "0.30"
    Mem/NotLinkedNodesKept: "false"
    Mem/STMSize: "30"
    Mem/LaserScanDownsampleStepSize: "1"
    Mem/IncrementalMemory: "true"
    Mem/InitWMWithAllNodes: "false"
    
    RGBD/OptimizeFromGraphEnd: "false"
    RGBD/ProximityPathMaxNeighbors: "0"
    RGBD/NeighborLinkRefining: "true"
    RGBD/CreateOccupancyGrid: "true"
    RGBD/LocalRadius: "5.0"
    RGBD/AngularUpdate: "0.1"
    RGBD/LinearUpdate: "0.1"
    
    Grid/FromDepth: "true"
    Grid/CellSize: "0.05"
    Grid/DepthMax: "4.0"
    Grid/DepthMin: "0.2"
    Grid/MaxObstacleHeight: "2.0"
    Grid/MaxGroundHeight: "0.1"
    Grid/MinGroundHeight: "-0.2"
    Grid/ClusterRadius: "0.1"
    Grid/MinClusterSize: "10"
    Grid/FlatObstacleDetected: "true"
    Grid/3D: "true"
    Grid/GroundIsObstacle: "false"
    Grid/NormalsSegmentation: "true"
    
    Vis/FeatureType: "6"
    Vis/MaxFeatures: "1000"
    Vis/MinInliers: "15"
    Vis/EstimationType: "1"
    Vis/ForwardEstOnly: "true"
    Vis/InlierDistance: "0.1"
    Vis/RefineIterations: "5"
    Vis/PnPReprojError: "2.0"
    Vis/EpipolarGeometryVar: "0.02"
    
    Kp/MaxFeatures: "400"
    Kp/BadSignRatio: "0.5"
    Kp/RoiRatios: "0.03 0.03 0.04 0.04"
    Kp/DetectorStrategy: "6"
    Kp/NNStrategy: "1"
    
    Optimizer/Strategy: "1"
    Optimizer/Iterations: "20"
    Optimizer/Epsilon: "0.00001"
    Optimizer/GravitySigma: "0.3"
    
    Icp/VoxelSize: "0.05"
    Icp/MaxCorrespondenceDistance: "0.1"
    Icp/MaxIterations: "30"
    Icp/CorrespondenceRatio: "0.1"
    
    DbSqlite3/InMemory: "false"
    DbSqlite3/CacheSize: "10000"