rviz2:
  ros__parameters:
    use_sim_time: true
    
    splash_screen: false
    
    frame_manager:
      fixed_frame_timeout: 10.0
      
    default_plugins:
      - rviz_default_plugins
      - rviz_common
      
    default_tool: "rviz_default_plugins/Interact"
    
    camera_type: "orbit"
    
    grid:
      enabled: true
      cell_count: 20
      cell_size: 1.0
      color: [0.5, 0.5, 0.5]
      
    tf:
      enabled: true
      marker_scale: 1.0
      show_names: true
      show_arrows: true
      show_axes: true