px4_controller:
  ros__parameters:
    # Control timing
    setpoint_rate_ms: 50
    
    # Flight parameters
    takeoff_altitude: 1.5
    teleop_position_step: 0.5
    yaw_step: 15.0
    
    # Control modes
    initial_control_mode: 0  # 0=MANUAL, 1=TELEOP, 2=AUTONOMOUS
    
    # Camera parameters
    camera_fov_horizontal: 90.0
    optimal_camera_distance: 3.0
    
    # Recovery parameters
    similarity_threshold: 2.0
    similarity_time_threshold: 30.0
    recovery_altitude_offset: 1.0
    recovery_backward_distance: 2.0
    recovery_maneuver_steps: 5
    navigation_step_size: 2.5

    camera_offset_x: 0.3  # Camera forward offset from drone center (meters)
    camera_offset_z: -0.15  # Camera down offset from drone center (meters