rtabmap:
  ros__parameters:
    use_sim_time: true
    frame_id: 'base_link'
    imu_frame_id: 'x500_depth_0/base_link/imu_sensor'
    map_frame_id: 'map'
    subscribe_depth: true
    subscribe_rgb: true
    subscribe_scan_cloud: true
    subscribe_odom_info: false
    approx_sync: true
    subscribe_imu: true
    wait_imu_to_init: false
    
    # RTAB-Map parameters for 3D mapping
    Rtabmap/DetectionRate: '1.0'
    Rtabmap/TimeThr: '0'
    Rtabmap/CreateIntermediateNodes: 'true'
    Rtabmap/MaxRetrieved: '2'
    Mem/RehearsalSimilarity: '0.6'
    Mem/NotLinkedNodesKept: 'false'
    Mem/STMSize: '30'
    Mem/LaserScanDownsampleStepSize: '1'
    Mem/UseOdomFeatures: 'true'
    Mem/DepthCompressionFormat: '.png'

    # Visual parameters - Updated for consistent feature detection
    Vis/EstimationType: '1'
    Vis/MaxDepth: '10.0'
    Vis/MinInliers: '12'
    Vis/InlierDistance: '0.1'
    Vis/FeatureType: '8'
    Vis/MaxFeatures: '1000'
    
    # Keypoint parameters - Add this to match Vis/FeatureType
    Kp/DetectorStrategy: '8'  # ORB detector (matches Vis/FeatureType)
    
    # Grid parameters for 3D occupancy
    Grid/3D: 'true'
    Grid/GroundIsObstacle: 'false'
    Grid/MaxObstacleHeight: '2.0'
    Grid/MaxGroundHeight: '0.1'
    Grid/NormalsSegmentation: 'false'
    Grid/CellSize: '0.1'
    Grid/RangeMax: '10.0'
    Grid/ClusterRadius: '0.1'
    Grid/MinClusterSize: '10'
    
    # ICP parameters
    Icp/VoxelSize: '0.1'
    Icp/MaxCorrespondenceDistance: '0.5'
    Icp/Strategy: '1'
    Icp/CorrespondenceRatio: '0.2'
    
    # Optimizer
    Optimizer/Strategy: '1'
    Optimizer/Iterations: '100'
    Optimizer/Epsilon: '0.00001'

    Rtabmap/DetectFrontiers: 'true'
    Rtabmap/FrontierNbNeighbours: '4'       # default: 4
    Rtabmap/FrontierClusterRadius: '0.3'    # cluster radius for frontier filtering


rtabmap_viz:
  ros__parameters:
    use_sim_time: true
    # Additional visualization parameters can be added here if needed 